name: Rust Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Create release archive
        run: |
          mkdir release
          cp target/release/onion_scraper release/
          cd release
          tar -czf onion_scraper-x86_64-unknown-linux-gnu.tar.gz onion_scraper

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/onion_scraper-x86_64-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
