name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir -p dist
          cp target/release/onion_scraper dist/
          cd dist
          tar -czvf onion_scraper-linux-x86_64.tar.gz onion_scraper

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/onion_scraper-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir -p dist
          cp target/release/onion_scraper dist/
          cd dist
          tar -czvf onion_scraper-macos-x86_64.tar.gz onion_scraper

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/onion_scraper-macos-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir dist
          copy target\release\onion_scraper.exe dist\
          powershell Compress-Archive -Path dist\onion_scraper.exe -DestinationPath dist\onion_scraper-windows-x86_64.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/onion_scraper-windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
